sudo: required
#ap related -->
dist: trusty
cache: pip
# <-- ap related
language: python
python:
- 2.7
install:
- "./install-dependencies.sh"
- tpip=$(which pip)
- "$tpip install -r requirements.txt"
- ls .
#to execute firefox in travisci
before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
- firefox --version
script:
- python testsite/manage.py makemigrations
- python testsite/manage.py migrate
- pwd
- ls .
after_success:
- ./run_regression.sh
addons:
  sauce_connect: true
  firefox: "49.0"
  # ap related -->
  postgresql: '9.3'
  # <-- ap related
#before_deploy:
#- ./run_regression.sh
#- test $TRAVIS_TEST_RESULT = 0 && ./run_regression.sh
deploy:
  - provider: heroku
    skip_cleanup: true
    api_key:
      secure: gWgzt6v+3SE6WL031EfCVFk+gg00CDVfTfbY+oaRnK52y5cKYWFVOF8hUYvdbREu7xrrBPIcPJXHqBA8fh+WXyQG5LHVCr+Hk8HfnhqmPvhLVLsST/B0vDL6C29v1/muTor18MaoZgAEAX/SasjNQCwZOm9cznDooQXBiPzRm9R3bxcDztyXTAT7DfT7MUyqYlm1wosFBvxNZP9yUjlNtAhiDydNmDIw5QSOyutAKYT6fb6/9MVDUPMLVZ1Fz6D5Z2Hp/mn2KQoOBnbY/URBz+IuuxS3GJh8WADo9xuhbNQKiPd8XHmiSnR6PnhpVcfkQknUVGIbBOKNtCO8n3+JuA0cztGC4BO5EXNcKm7/nITkcI2+2tqEUT7dLcLspk5q+xYftAIDl9HXflqwWvIwQxPfrNNg+XkX9C0czXuI6gZtZIrpJPgpF3qn/2tC0MePbl2EO2RBsj8XfGhcNNnnCcnxfxlxWSiXOjmAJmez2EF58SM7PPAZdFxIFRWSTvpSYpSDxhnV8NlpBvN+3BYehXcykyXBKmK69NJvFHH7+NtFVxgHbl/6aI5AlLat6JdVTSqV8tiAfiqdwSJ2Wmq1TLlWgZyMX88t6vFEhNGfa/DGzhvrzweeHJsPEniaormLjmRUjnrsCQ2lL/tNxHDIiAMgDxZv10EdkZfacv+uGVg=
    on:
      branch: master
    app: test-travisci-heroku
    run:
    - ls .
    - tpython=$(which python)
    - "$tpython testsite/manage.py makemigrations"
    - "$tpython testsite/manage.py migrate"
    - restart
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: G39fisZBxQD0QIhBTx4SRth/Ewo6nHVFnlItuq+ZmOp3WCn9tvFbxCpCP5wqg7+oP0AcOKnPSDHk5hDLEI1f48Z7WCWbVYMWtQYaDONB0Uc1vWF2EkCjBC5lZcTtMuuPwcmt3wGRlsRP5UStOyJbJqxLl7EBjxeCRKm6r+h+ekZbnIlKqRKDBbqZGCBqD1xkUa5nvsEPrEI5GsLVceQqI9i1QmBUv4rHHhUHJ1Jwaxb6n5SaO4CK21i+3gmc6iX7QkmDjdO/MmY50yvcOz1YyegFqa6pCpniLJJOPR6wvnjCpl8FocSxkb1ftBLweGp9DqJEbRfcMUty72fiRvTuCqlsnzDGzYueLr/5TuIyCEA9VXwNe1AzQ+SE36R0YNZkwBJUMaEhMBu+vQSzpZN/mYkb+Pf+pX7t4iTHytyc5E1Pvn35jSH6qeV8D5EtqPikra9HKGIPA4ecNhRrs6F+7otd522AOMNwjr0Y/bLUOBBrNmLz0wfIr7UCf2pY6Bbwswqu6WPpOliG41MAhBQTvil5sjD9i3gxS/GzMTU4N9bpr0HDEW3LUt6BmHM2Z6iXrSpPqB5eKI0/YHTNar5j8smZ+OjQSSxa/tK6Wp1bVUQkUWOb5Qz8KajuoQ5E1bvKDi/aI/gXBQH0VeXsM+eV/aEas6O0B7jNRxUJCtOjQ38=
    file_glob: true
    file: $TRAVIS_BUILD_DIR/saucelab/djattendance/selenium/automation/reports/*
    on:
      tags: true
#    overwrite: true
#after_deploy:
#- ./run_regression.sh
##### REGRESSION TEST RUN IDEA #####
# e.g.
#- python testsite/manage.py runserver &
#- mkdir saucelab; cd saucelab
#- git clone -b selenium https://github.com/swenghj/test-travisci-sourcelab.git
#- cd test-travisci-sourcelab
#- ls .
#- cd selenium/automation
#- python demo-regression.py
#- ls reports
#- git config --global user.name "My Name"
#- git config --global user.email "me@example.com"
#- git branch htmlresults selenium
#- git checkout htmlresults
#- git add reports/* -f
#- git commit -m "regression results HTMLs"
#- git push https://$GIT_USER:$GIT_API_KEY@github.com/swenghj/test-travisci-sourcelab.git htmlresults -f
notifications:
  email:
    recipients:
    - yaui80@yahoo.com
    on_success: always
    on_failure: always
env:
  global:
  - secure: Ustn65jLoW3uT0qtZGfMKA+DE80/oTGhCc1OARWhHofHqn293H4fB0FhHqXaRo5ViiQ2Z4SieoOPmAmXkG1WQAV0m7kr9nM+3hwLR5F23T7oL/IgElelOwon49EgltbCPg6I9+silZvXTQqefg2ZqEyTCXwIy4tgY5lUnPfM8vnJGnJmm72Pzg598A2jMnMOR7xYeJoA2Se+6R8ehO2T3XdeJXXq//iv+m3HcF704bA1SeaVqgpGCowb8Mv6HDlGGbY/nqOkK91ElMv8kiWgkkFbVThYkATCX6e6JAMog0th6y8eCmBrK6+0SUWz9EoOKmrrGeBT3LCsvAelBl8zQa44NRPs4ekAT2dRdY11xj+UredVLVS+hmf30/9omOnkvy2jKmO5q/EdRZXUOy9isU0a8K5/vnRqYJ8h0+6KWkaR4MgjTGkpV67t0tQ/qxNHcm5ta+xYCry2fB5Hjo2vcwPImu6g+AObhs3InWTpq4FT4b0IxHYGoZ1o8DfmK0EiY3YUx25kJDsz1/24tPEdbkmPLo5j2HbQPgkDuWEBuhcX6k3eUd4kK9RAdZpBNURYVpO6E5yl3WhBX3Tlx1aYCfHFls2XuXSWsmEYEVVThULRsLIuCxb0thp4bf6W2teuraDsnSOMhv9sypdhewAjCG6NdJka/nwdB4kV5WleCFc=
  - secure: K6EN3/kerUCSCRyfd38cEpxP3af3/8Wlrubb3JnH4ZcG/IT35Aosl1ManGsjG9pMdOLIIpiPTcIj2vToU88XJ4/tkshjrMYcNqz0e7nMpaZQBKo4F7bb9lXXzd0AKcLxCd5oIc2B0LR/kCs+/Xh5IlLj9y/pWIWwKh1WjT+wbL4rOjrFW8vjdHtXFX/ASTt8XO8Oof9MnKEgopx4IkCWuBJTvfHOirU9bpuMMypoCWyi4gp4vVxeuCfriAb2AzwYL2oGBAHbqzgQyBJtbtdiF7xW6+oJAhqmQtE8YJ+dtqL+OVpx09lzhjEBanuXd5zo33MnlCi90q52DF8P6aswSEdqiVuW5KDd49/i3LwG/4hGPVscbM71OHG6VrHb6SEN5AAxrFm8QED0CKlIWzz4Czj5L+3/kvRAItNMqi9Vu/y2JjFTsjAxTilKiZN3LhK3OUjc9IvMQrHzNBvxZWlTag8qpNzH6OIFbcgiwoR5n2isnD2rofkNZP0nfNprsM2r0R4vBTI40DNxeqYNNYUXzLvP/HMeA5RFJqRbI7nuPLdwCFtV9UM/Q6i8GNGCOV3NsfKb0n9vDiP+DJP/dIK6zjVRtG7WWDUL+qmZRjtDJFC/DW90cN1KwcKO9FNfH8UUPxvFAe7xq7x31gkNb1RXxj3Ejd1P6xxVVOk+pxCKThA=
