sudo: required
language: python
python:
  - 2.7
# command to install dependencies
install: 
  - ./install-dependencies.sh
  - tpip=$(which pip)
  - $tpip install -r requirements.txt
# command to run tests
script: pytest



